server.port: 8001

logging.level.root: info

#spring的数据源配置
spring.datasource:
  url: jdbc:mysql://localhost:3306/springbootsecurity
  username: root
  password: root
  driverClassName: com.mysql.jdbc.Driver

spring.jpa:
  database: MYSQL
  show-sql: true
  hibernate.ddl-auto: update
  hibernate.naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
  properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
